# Generated by Django 5.2.4 on 2025-07-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricealert',
            name='user_whatsapp_id',
            field=models.CharField(max_length=30),
        ),
    ]
